### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [1]:
import pandas as pd
police_shots = pd.read_csv('US Police shootings in from 2015-22.csv')
police_shots.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,longitude,latitude,is_geocoding_exact
0,1,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False,-123.122,47.247,True
1,2,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False,-122.892,45.487,True
2,3,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False,-97.281,37.695,True
3,4,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False,-122.422,37.763,True
4,5,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False,-104.692,40.384,True

In [3]:
police_shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7682 entries, 0 to 7681
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       7682 non-null   int64
 1   name                     7275 non-null   object
 2   date                     7682 non-null   object
 3   manner_of_death          7682 non-null   object
 4   armed                    7473 non-null   object
 5   age                      7210 non-null   float64
 6   gender                   7663 non-null   object
 7   race                     6244 non-null   object
 8   city                     7682 non-null   object
 9   state                    7682 non-null   object
 10  signs_of_mental_illness  7682 non-null   bool
 11  threat_level             7682 non-null   object
 12  flee                     6819 non-null   object
 13  body_camera              7682 non-null   bool
 14  longitude                6847 non-null   float64
 15  latitude                 6847 non-null   float64
 16  is_geocoding_exact       7682 non-null   bool
dtypes: bool(3), float64(3), int64(1), object(10)
memory usage: 862.8+ KB

In [5]:
police_shots.shape

(7682, 17)

In [6]:
police_shots.describe()

                id          age    longitude     latitude
count  7682.000000  7210.000000  6847.000000  6847.000000
mean   3841.500000    37.161997   -97.057301    36.668453
std    2217.746717    12.951797    16.593304     5.394855
min       1.000000     2.000000  -160.007000    19.498000
25%    1921.250000    27.000000  -112.040500    33.478500
50%    3841.500000    35.000000   -94.249000    36.095000
75%    5761.750000    45.000000   -83.080500    40.026500
max    7682.000000    92.000000   -67.867000    71.301000

In [10]:
police_shots.isnull().sum()

id                            0
name                        407
date                          0
manner_of_death               0
armed                       209
age                         472
gender                       19
race                       1438
city                          0
state                         0
signs_of_mental_illness       0
threat_level                  0
flee                        863
body_camera                   0
longitude                   835
latitude                    835
is_geocoding_exact            0
dtype: int64

In [18]:
police_shots['manner_of_death'].unique()

array(['shot', 'shot and Tasered'], dtype=object)

In [19]:
police_shots['armed'].unique()

array(['gun', 'unarmed', 'toy weapon', 'nail gun', 'knife', nan, 'shovel',
       'vehicle', 'hammer', 'hatchet', 'sword', 'machete', 'box cutter',
       'undetermined', 'metal object', 'screwdriver', 'lawn mower blade',
       'flagpole', 'guns and explosives', 'cordless drill', 'crossbow',
       'BB gun', 'metal pole', 'Taser', 'metal pipe', 'metal hand tool',
       'blunt object', 'metal stick', 'sharp object', 'meat cleaver',
       'carjack', 'chain', "contractor's level", 'railroad spikes',
       'stapler', 'beer bottle', 'unknown weapon', 'binoculars',
       'pellet gun', 'bean-bag gun', 'baseball bat and fireplace poker',
       'straight edge razor', 'gun and knife', 'ax', 'brick',
       'baseball bat', 'hand torch', 'chain saw', 'garden tool',
       'pair of scissors', 'pole', 'pick-axe', 'flashlight', 'baton',
       'spear', 'chair', 'pitchfork', 'hatchet and gun', 'rock',
       'piece of wood', 'pipe', 'glass shard', 'motorcycle',
       'pepper spray', 'metal rake', 'crowbar', 'oar', 'machete and gun',
       'tire iron', 'air conditioner', 'pole and knife',
       'baseball bat and bottle', 'fireworks', 'pen', 'chainsaw',
       'gun and sword', 'gun and car', 'claimed to be armed',
       'incendiary device', 'samurai sword', 'bow and arrow',
       'gun and vehicle', 'vehicle and gun', 'wrench', 'walking stick',
       'barstool', 'BB gun and vehicle', 'wasp spray', 'air pistol',
       'Airsoft pistol', 'baseball bat and knife', 'vehicle and machete',
       'ice pick', 'car, knife and mace', 'bottle', 'gun and machete',
       'microphone', 'knife and vehicle', 'machete and hammer', 'stake',
       'incendiary weapon', 'ax and machete', 'hammer and garden tool',
       'flare gun'], dtype=object)

In [20]:
police_shots['gender'].unique()

array(['M', 'F', nan], dtype=object)

In [21]:
police_shots.groupby(['armed']).id.count()

armed
Airsoft pistol          6
BB gun                 18
BB gun and vehicle      1
Taser                  38
air conditioner         1
                       ..
vehicle and gun         9
vehicle and machete     1
walking stick           1
wasp spray              1
wrench                  1
Name: id, Length: 103, dtype: int64

### Numpy

In [23]:
import numpy as np

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [24]:
a = np.array([[1, -2, 4], [2, 0, -1]])
b = np.array([[5, 2, 3], [4, 6,2]])

a + b, a - b

(array([[6, 0, 7],
        [6, 6, 1]]),
 array([[-4, -4,  1],
        [-2, -6, -3]]))

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [26]:
a = np.array([[1, 2], [2, -1], [3, 0]])
b = np.array([[-1, 1], [1, 2], [0, 0]])
a - 3*b

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [27]:
a = np.array([[1, -1], [2, 0], [3, 0]])
b = np.array([[1, 1], [2, 0]])

a.dot(b)

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [28]:
a = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(a)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [30]:
a = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])
obr_a = np.linalg.inv(a)
obr_a

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [32]:
a.dot(obr_a)

array([[ 1.00000000e+00, -2.77555756e-17,  1.38777878e-16],
       [ 2.77555756e-17,  1.00000000e+00,  2.77555756e-17],
       [-5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])